### ISSUE TITLE
Fixnout CSSka hlavičky webu na mobilu

### ISSUE THREAD

**Issue by exyi** [ksp/kurz#36]
Default CSSka KSPího webu se na mobilu docela podivně rozbíjejí. To teda platí všude, nejen u našeho grafu. Předělat horní menu na flexbox či ještě lépe celé menu na mobilu skrývat by mohlo docela pomoct.

https://gitea.ks.matfyz.cz/KSP/graf-uloh/issues/36

**Comment by vakabus** [comment]
Vyřešeno responzivními CSSky na celém KSPím webu...
