### ISSUE TITLE
Nefunguje zobrazování videí v zadání úloh

### ISSUE THREAD

**Issue by vakabus** [ksp/kurz#76]
viz [34-1-S](https://ksp.mff.cuni.cz/h/ulohy/34/zadani1.html#task-34-1-S)

**Comment by JiriKalvoda** [comment]
Stejný problém u 34-2-S. Pokud máte stále zájem v kurzu zobrazovat aktuální úlohy tak by bylo fajn ho opravit.
V opačném případě prosím větev s aktuálními úlohami schovejte a nechte jen statickou část obsahující archiv hezkých úloh, která funguje mnohem bezchybněji.

Děuji

**Comment by JiriKalvoda** [comment]
Nainstaloval jsi to na ostrý web?

**Comment by vakabus** [comment]
Nasazeno. Byly tam problémy během instalace s tím, že na serveru máme Node v10, který už nikdo dávno nepodporuje...
